import { useEffect, useMemo, useState } from 'react';
import { BookOpen, Check, ExternalLink, Filter, Search, Star, Tag, X } from 'lucide-react';
import type { SiteRecord } from '../domain/types';

export function LibraryWorkspace({ sites, onOpen, onToggleFavorite, onChange }: { sites: SiteRecord[]; onOpen: (site: SiteRecord) => void; onToggleFavorite: (title: string) => void; onChange: (sites: SiteRecord[] | ((current: SiteRecord[]) => SiteRecord[])) => void; initialTag?: string }) {
  const [query, setQuery] = useState('');
  const [tag, setTag] = useState('Все');
  const [type, setType] = useState<'Все' | 'С заметками' | 'Избранное'>('Все');
  const [selected, setSelected] = useState<string[]>([]); const [bulkTag, setBulkTag] = useState('');
  const tags = ['Все', ...Array.from(new Set(sites.flatMap(site => site.tags ?? []))).sort()];
  const items = useMemo(() => sites.filter(site => {
    const needle = query.toLowerCase().trim();
    const matchesQuery = !needle || `${site.title} ${site.domain} ${site.desc} ${(site.tags ?? []).join(' ')}`.toLowerCase().includes(needle);
    const matchesTag = tag === 'Все' || site.tags?.includes(tag);
    const matchesType = type === 'Все' || (type === 'С заметками' ? Boolean(site.note) : Boolean(site.favorite));
    return matchesQuery && matchesTag && matchesType;
  }), [sites, query, tag, type]);
  return <div className="library-workspace"><div className="library-toolbar"><div className="library-search"><Search size={16}/><input aria-label="Поиск в библиотеке" value={query} onChange={event => setQuery(event.target.value)} placeholder="Поиск по материалам..."/></div><div className="library-filters"><button className={type==='Все'?'active':''} onClick={()=>setType('Все')}>Все материалы <b>{sites.length}</b></button><button className={type==='С заметками'?'active':''} onClick={()=>setType('С заметками')}>С заметками</button><button className={type==='Избранное'?'active':''} onClick={()=>setType('Избранное')}>Избранное</button></div></div><div className="library-tags"><Tag size={14}/>{tags.map(item=><button key={item} className={tag===item?'active':''} onClick={()=>setTag(item)}>{item}</button>)}<span><Filter size={13}/> {items.length} материалов</span></div>{selected.length>0&&<div className="library-bulk"><b>Выбрано: {selected.length}</b><button onClick={()=>setSelected([])}>Снять выбор</button><select aria-label="Тег для выбранных материалов" value={bulkTag} onChange={event=>setBulkTag(event.target.value)}><option value="">Добавить тег...</option>{tags.filter(item=>item!=='Все').map(item=><option key={item}>{item}</option>)}</select><button disabled={!bulkTag} onClick={()=>{onChange(items=>items.map(site=>selected.includes(site.title)?{...site,tags:Array.from(new Set([...(site.tags??[]),bulkTag]))}:site));setSelected([]);setBulkTag('')}}><Tag size={14}/> Применить тег</button><button onClick={()=>setSelected([])}><X size={14}/> Снять выбор</button></div>}<div className="library-grid">{items.map(site=><article draggable onDragStart={event=>{event.dataTransfer.setData('nexus-site',site.title);event.dataTransfer.effectAllowed='copy'}} className={'library-card glass '+(selected.includes(site.title)?'selected':'')} key={site.title} onClick={()=>onOpen(site)}><button className="library-check" aria-label={'Выбрать '+site.title} onClick={event=>{event.stopPropagation();setSelected(value=>value.includes(site.title)?value.filter(item=>item!==site.title):[...value,site.title])}}>{selected.includes(site.title)&&<Check size={13}/>}</button><div className="library-card-media" style={{background:site.color}}><span>{site.icon}</span></div><div className="library-card-body"><div className="library-card-title"><h3>{site.title}</h3><button aria-label={site.favorite?'Убрать из избранного':'Добавить в избранное'} onClick={event=>{event.stopPropagation();onToggleFavorite(site.title)}}><Star size={15} fill={site.favorite?'currentColor':'none'}/></button></div><p>{site.desc}</p><small>{site.domain}</small><div className="library-card-tags">{(site.tags??[]).map(item=><span key={item}>{item}</span>)}{site.note&&<span>Заметка</span>}</div></div><ExternalLink className="library-open" size={15}/></article>)}</div>{!items.length&&<div className="empty"><BookOpen size={30}/><b>Материалы не найдены</b><span>Измените фильтры или добавьте tags к сайтам</span></div>}</div>
}
