import { useState } from 'react';
import { BriefcaseBusiness, Folder, FolderPlus, MoreHorizontal, Plus, Trash2 } from 'lucide-react';
import type { Project, SiteRecord } from '../domain/types';

export function ProjectsWorkspace({ projects, sites, onChange, onSelect }: { projects: Project[]; sites: SiteRecord[]; onChange: (projects: Project[] | ((current: Project[]) => Project[])) => void; onSelect: (project: Project) => void }) {
  const [creating, setCreating] = useState(false);
  const [name, setName] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const activeProject = projects.find(project => project.id === selectedId);
  const create = () => { const clean = name.trim(); if (!clean) return; const now = Date.now(); onChange(items => [...items, { id: `project-${now}`, name: clean, color: '#3988ee', icon: clean[0].toUpperCase(), siteIds: [], createdAt: now, updatedAt: now }]); setName(''); setCreating(false); };
  return <div className="projects-workspace"><div className="projects-hero"><div><span className="eyebrow">РАБОЧИЕ ПРОСТРАНСТВА</span><h2>Проекты</h2><p>Соберите сайты, материалы и заметки вокруг одной задачи.</p></div><button className="add-button" onClick={() => setCreating(true)}><FolderPlus size={17}/> Новый проект</button></div>{creating && <div className="project-create glass"><input autoFocus aria-label="Название проекта" value={name} onChange={event => setName(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') create(); if (event.key === 'Escape') setCreating(false); }} placeholder="Название проекта"/><button onClick={create}>Создать</button><button onClick={() => setCreating(false)}>Отмена</button></div>}<div className="project-stats"><div><b>{projects.length}</b><span>проектов</span></div><div><b>{sites.length}</b><span>сайтов в workspace</span></div><div><b>{projects.filter(project => project.siteIds.length > 0).length}</b><span>активных</span></div></div><div className="project-grid">{projects.map(project => <article className={'project-card glass ' + (selectedId === project.id ? 'selected' : '')} key={project.id} onClick={() => { setSelectedId(project.id); onSelect(project); }}><div className="project-card-top"><span className="project-icon" style={{ background: project.color }}><Folder size={18}/></span><button aria-label={`Удалить проект ${project.name}`} onClick={event => { event.stopPropagation(); onChange(items => items.filter(item => item.id !== project.id)); if (selectedId === project.id) setSelectedId(null); }}><Trash2 size={15}/></button></div><h3>{project.name}</h3><p>{project.siteIds.length || sites.filter(site => site.category === project.name).length} сайтов</p><div className="project-card-footer"><BriefcaseBusiness size={14}/> Открыть пространство <MoreHorizontal size={15}/></div></article>)}<button className="project-add-card" onClick={() => setCreating(true)}><Plus size={22}/><b>Создать проект</b><span>Новый рабочий контекст</span></button></div>{activeProject && <section className="project-detail glass"><header><div><span className="eyebrow">ПРОЕКТ</span><h3>{activeProject.name}</h3><p>Выберите сайты, которые относятся к этому рабочему пространству.</p></div><button onClick={() => setSelectedId(null)}>Закрыть</button></header><div className="project-sites">{sites.map(site => <label key={site.title} className={activeProject.siteIds.includes(site.title) ? 'assigned' : ''}><input type="checkbox" checked={activeProject.siteIds.includes(site.title)} onChange={() => onChange(items => items.map(item => item.id === activeProject.id ? { ...item, siteIds: item.siteIds.includes(site.title) ? item.siteIds.filter(id => id !== site.title) : [...item.siteIds, site.title], updatedAt: Date.now() } : item))}/><span className="project-site-icon" style={{ background: site.color }}>{site.icon}</span><span><b>{site.title}</b><small>{site.domain}</small></span></label>)}</div></section>}</div>;
}
