import { useMemo, useState } from 'react';
import { Check, Hash, Merge, Plus, Tag, Trash2 } from 'lucide-react';
import type { SiteRecord } from '../domain/types';

export function TagsWorkspace({ sites, onChange }: { sites: SiteRecord[]; onChange: (sites: SiteRecord[] | ((current: SiteRecord[]) => SiteRecord[])) => void }) {
  const [query, setQuery] = useState(''); const [newTag, setNewTag] = useState(''); const [selected, setSelected] = useState<string | null>(null);
  const tags = useMemo(() => Array.from(new Set(sites.flatMap(site => site.tags ?? []))).sort().map(name => ({ name, count: sites.filter(site => site.tags?.includes(name)).length })), [sites]);
  const visible = tags.filter(tag => tag.name.toLowerCase().includes(query.toLowerCase()));
  const addTag = () => { const clean=newTag.trim(); if(!clean)return; onChange(items=>items.map(site=>site.tags?.includes(clean)?site:{...site,tags:[...(site.tags??[]),clean]})); setNewTag(''); };
  const removeTag = (name:string) => onChange(items=>items.map(site=>({...site,tags:(site.tags??[]).filter(tag=>tag!==name)})));
  const renameTag = (name:string) => { const next=prompt('Новое название тега',name)?.trim(); if(next&&next!==name)onChange(items=>items.map(site=>({...site,tags:(site.tags??[]).map(tag=>tag===name?next:tag)}))); };
  return <div className="tags-workspace"><div className="tags-hero"><div><span className="eyebrow">ОРГАНИЗАЦИЯ</span><h2>Теги и категории</h2><p>Связывайте сайты и материалы по темам, статусам и задачам.</p></div><div className="tag-create"><input aria-label="Новый тег" value={newTag} onChange={event=>setNewTag(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')addTag()}} placeholder="Новый тег"/><button onClick={addTag}><Plus size={15}/> Добавить</button></div></div><div className="tags-toolbar"><div className="tags-search"><Hash size={15}/><input aria-label="Поиск тегов" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Поиск тегов..."/></div><span>{tags.length} тегов · {sites.filter(site=>site.tags?.length).length} сайтов с тегами</span></div><div className="tags-grid">{visible.map(tag=><article className={'tag-card glass '+(selected===tag.name?'selected':'')} key={tag.name} onClick={()=>setSelected(tag.name)}><div className="tag-card-head"><span><Tag size={16}/></span><button aria-label={`Удалить тег ${tag.name}`} onClick={event=>{event.stopPropagation();removeTag(tag.name)}}><Trash2 size={14}/></button></div><h3>{tag.name}</h3><p>{tag.count} {tag.count===1?'сайт':'сайтов'}</p><div className="tag-card-actions"><button onClick={event=>{event.stopPropagation();renameTag(tag.name)}}><Merge size={13}/> Переименовать</button><button className="tag-select" onClick={event=>{event.stopPropagation();setSelected(tag.name)}}><Check size={13}/> Открыть</button></div></article>)}</div>{selected&&<section className="tag-detail glass"><div><span className="eyebrow">ВЫБРАННЫЙ ТЕГ</span><h3>#{selected}</h3><p>Сайты, связанные с этим тегом, доступны в Library.</p></div><button onClick={()=>setSelected(null)}>Закрыть</button></section>}{!visible.length&&<div className="empty"><Tag size={30}/><b>Теги пока не созданы</b><span>Добавьте тег к сайту через форму добавления</span></div>}</div>;
}
