import { BriefcaseBusiness, ChevronRight, FolderKanban, Home, Menu, Pencil, Plus, Tag, X } from 'lucide-react';
import type { MouseEvent } from 'react';
import { useAppStore } from '../../state/useAppStore.ts';
import { GlassSurface } from '../primitives/GlassSurface.tsx';
import styles from './MobileNavigation.module.css';
export function MobileNavigation(){
 const open=useAppStore(state=>state.mobileNavOpen);const setOpen=useAppStore(state=>state.setMobileNavOpen);const projects=useAppStore(state=>state.projects);const categories=useAppStore(state=>state.categories);const activeProject=useAppStore(state=>state.activeProjectId);const activeCategory=useAppStore(state=>state.activeCategoryId);const setProject=useAppStore(state=>state.setActiveProject);const setCategory=useAppStore(state=>state.setActiveCategory);const setStructureEditor=useAppStore(state=>state.setStructureEditor);
 const roots=categories.filter(category=>category.projectId===activeProject&&!category.parentId);
 return <><GlassSurface role="control" className={styles.bar}><button aria-label="Открыть разделы" onClick={()=>setOpen(true)}><Menu size={20}/></button><div className={styles.brand}><span>N</span><strong>Nexus</strong></div><div className={styles.compactStatus}><b>09:42</b><span>22°</span></div></GlassSurface>{open&&<div className={styles.layer} role="presentation" onMouseDown={()=>setOpen(false)}><GlassSurface as="aside" role="popover" className={styles.drawer} onMouseDown={(event:MouseEvent<HTMLElement>)=>event.stopPropagation()}><header><div><strong>Nexus</strong><small>Разделы и категории</small></div><button aria-label="Закрыть разделы" onClick={()=>setOpen(false)}><X size={20}/></button></header><section><h3>Проекты</h3><div className={styles.projects}>{projects.map(project=>{const Icon=project.id==='home'?Home:project.id==='project'?FolderKanban:BriefcaseBusiness;return <div className={styles.projectItem} key={project.id}><button className={activeProject===project.id?styles.active:''} onClick={()=>{setProject(project.id);setOpen(false)}}><Icon size={18}/><span>{project.name}</span></button><button className={styles.projectEdit} aria-label={`Изменить ${project.name}`} onClick={()=>{setOpen(false);setStructureEditor({kind:'project',id:project.id})}}><Pencil size={12}/></button></div>})}<button onClick={()=>{setOpen(false);setStructureEditor({kind:'project'})}}><Plus size={18}/><span>Добавить</span></button></div></section><section><h3>Категории</h3><div className={styles.categories}>{roots.map(category=><button key={category.id} className={activeCategory===category.id?styles.active:''} onClick={()=>{setCategory(category.id);setOpen(false)}}><Tag size={19}/><span>{category.name}</span><ChevronRight size={16}/></button>)}<button onClick={()=>{setOpen(false);setStructureEditor({kind:'category'})}}><Plus size={18}/><span>Добавить категорию</span></button></div></section></GlassSurface></div>}</>;
}
