import { BriefcaseBusiness, ChevronDown, CircleDollarSign, FolderKanban, Grid2X2, Home, MessageCircle, Pencil, Plus, ShoppingCart, Users, Wrench } from 'lucide-react';
import { GlassSurface } from '../primitives/GlassSurface.tsx';
import { useAppStore } from '../../state/useAppStore.ts';
import styles from './Sidebar.module.css';
import { useLiveClock } from '../clock/useLiveClock.ts';
const iconFor=(name:string)=>name==='home'?Home:name==='finance'?CircleDollarSign:name==='shopping'?ShoppingCart:name==='tools'?Wrench:name==='social'?Users:name==='services'?Grid2X2:name==='entertainment'?MessageCircle:BriefcaseBusiness;
export function Sidebar(){
 const clock=useLiveClock();const projects=useAppStore(state=>state.projects);const categories=useAppStore(state=>state.categories);const sites=useAppStore(state=>state.sites);const activeProjectId=useAppStore(state=>state.activeProjectId);const activeCategoryId=useAppStore(state=>state.activeCategoryId);const setActiveProject=useAppStore(state=>state.setActiveProject);const setActiveCategory=useAppStore(state=>state.setActiveCategory);const setCalendarOpen=useAppStore(state=>state.setCalendarOpen);const setStructureEditor=useAppStore(state=>state.setStructureEditor);const projectCategories=categories.filter(category=>category.projectId===activeProjectId);const roots=projectCategories.filter(category=>!category.parentId);const countFor=(id:string)=>{const childIds=projectCategories.filter(c=>c.parentId===id).map(c=>c.id);return sites.filter(site=>site.projectId===activeProjectId&&[id,...childIds].includes(site.categoryId??'')).length};
 return <GlassSurface as="aside" role="panel" className={styles.sidebar}><div className={styles.brand}><span className={styles.brandMark}>N</span><div><strong>Nexus</strong><small>Speed Dial</small></div></div><GlassSurface role="control" className={styles.clockCard}><div className={styles.clockTop}><div><div className={styles.clock}>{clock.time}</div><button data-testid="date-button" onClick={()=>setCalendarOpen(true)}>{clock.date}</button></div><span className={styles.sun}>☀</span></div><div className={styles.weather}><span className={styles.weatherIcon}>🌤️</span><span className={styles.temp}>22°</span><span><b>Облачно</b><small>Ощущается как 21°</small></span></div></GlassSurface><section className={styles.section}><header>ПРОЕКТЫ <button aria-label="Добавить проект" onClick={()=>setStructureEditor({kind:'project'})}><Plus size={15}/></button></header><div className={styles.chips}>{projects.map(project=>{const Icon=project.id==='home'?Home:project.id==='project'?FolderKanban:BriefcaseBusiness;return <div className={styles.projectChip} key={project.id}><button className={project.id===activeProjectId?styles.activeChip:''} onClick={()=>setActiveProject(project.id)}><Icon size={14}/> {project.name}</button><button className={styles.chipEdit} aria-label={`Изменить ${project.name}`} onClick={()=>setStructureEditor({kind:'project',id:project.id})}><Pencil size={11}/></button></div>})}</div></section><section className={styles.section}><header>КАТЕГОРИИ <button aria-label="Добавить категорию" onClick={()=>setStructureEditor({kind:'category'})}><Plus size={15}/></button></header><div className={styles.chips}>{roots.slice(0,3).map(category=><button key={category.id} className={category.id===activeCategoryId?styles.activeChip:''} onClick={()=>setActiveCategory(category.id)}>{category.name}</button>)}</div></section><section className={`${styles.section} ${styles.explorer}`}><header>ПРОВОДНИК</header>{roots.map(root=>{const Icon=iconFor(root.id);const children=projectCategories.filter(c=>c.parentId===root.id);return <div key={root.id}><div className={styles.treeLine}><button className={`${styles.treeRow} ${root.id===activeCategoryId?styles.activeRow:''}`} onClick={()=>setActiveCategory(root.id)}><span><Icon size={15}/>{root.name}</span><em>{countFor(root.id)}</em><ChevronDown size={13}/></button><button className={styles.treeEdit} aria-label={`Изменить ${root.name}`} onClick={()=>setStructureEditor({kind:'category',id:root.id})}><Pencil size={12}/></button></div>{children.length>0&&<div className={styles.children}>{children.map(child=><button key={child.id} onClick={()=>setActiveCategory(child.id)}><span>• {child.name}</span><em>{countFor(child.id)}</em></button>)}</div>}</div>})}</section><button className={styles.addCategory} onClick={()=>setStructureEditor({kind:'category'})}><Plus size={16}/> Добавить категорию</button></GlassSurface>;
}
