import { BriefcaseBusiness, ChevronDown, CircleDollarSign, Grid2X2, Home, MessageCircle, Plus, ShoppingCart, Users, Wrench } from 'lucide-react';
import { GlassSurface } from '../primitives/GlassSurface.tsx';
import { seedCategories, seedProjects } from '../../data/seed.ts';
import { useAppStore } from '../../state/useAppStore.ts';
import styles from './Sidebar.module.css';

const sectionRows = [['social','Социальные сети',Users,3],['services','Сервисы',Grid2X2,8],['productivity','Продуктивность',BriefcaseBusiness,7],['entertainment','Развлечения',MessageCircle,6],['tools','Инструменты',Wrench,9],['shopping','Покупки',ShoppingCart,5],['finance','Финансы',CircleDollarSign,4]] as const;

export function Sidebar(){
 const activeProjectId=useAppStore(s=>s.activeProjectId);const activeCategoryId=useAppStore(s=>s.activeCategoryId);const setActiveProject=useAppStore(s=>s.setActiveProject);const setActiveCategory=useAppStore(s=>s.setActiveCategory);const setCalendarOpen=useAppStore(s=>s.setCalendarOpen);
 return <GlassSurface as="aside" role="panel" className={styles.sidebar}><div className={styles.brand}><span className={styles.brandMark}>N</span><div><strong>Nexus</strong><small>Speed Dial</small></div></div><GlassSurface role="control" className={styles.clockCard}><div className={styles.clockTop}><div><div className={styles.clock}>09:42</div><button data-testid="date-button" onClick={()=>setCalendarOpen(true)}>Четверг, 28 мая 2026</button></div><span className={styles.sun}>☀</span></div><div className={styles.weather}><span className={styles.weatherIcon}>🌤️</span><span className={styles.temp}>22°</span><span><b>Облачно</b><small>Ощущается как 21°</small></span></div><div className={styles.forecast}>{[['Пт','23°'],['Сб','24°'],['Вс','26°'],['Пн','22°']].map(([d,t])=><span key={d}>{d}<b>{t}</b></span>)}</div></GlassSurface><section className={styles.section}><header>ПРОЕКТЫ <button aria-label="Добавить проект"><Plus size={15}/></button></header><div className={styles.chips}>{seedProjects.map(project=><button key={project.id} className={project.id===activeProjectId?styles.activeChip:''} onClick={()=>setActiveProject(project.id)}>{project.id==='home'&&<Home size={14}/>} {project.name}</button>)}</div></section><section className={styles.section}><header>КАТЕГОРИИ <button aria-label="Добавить категорию"><Plus size={15}/></button></header><div className={styles.chips}>{seedCategories.filter(c=>!c.parentId).slice(0,2).map(category=><button key={category.id} className={category.id===activeCategoryId?styles.activeChip:''} onClick={()=>setActiveCategory(category.id)}>{category.name}</button>)}</div></section><section className={`${styles.section} ${styles.explorer}`}><header>ПРОВОДНИК</header>{sectionRows.map(([id,label,Icon,count],index)=><div key={id}><button className={`${styles.treeRow} ${id===activeCategoryId||(!activeCategoryId&&index===0)?styles.activeRow:''}`} onClick={()=>setActiveCategory(id)}><span><Icon size={15}/>{label}</span><em>{count}</em><ChevronDown size={13}/></button>{id==='social'&&<div className={styles.children}>{[['Общение',6],['Новости',5],['Чат',3]].map(([name,n])=><button key={name}><span>• {name}</span><em>{n}</em></button>)}</div>}</div>)}</section><button className={styles.addCategory}><Plus size={16}/> Добавить категорию</button></GlassSurface>;
}
