import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, ChevronLeft, ChevronRight, Star, ShieldCheck, UserRound, CloudSun, Plus, Home, Heart, Clock3, Download, StickyNote, Settings as SettingsIcon, Grid2X2, List, SlidersHorizontal, MoreHorizontal, ExternalLink, CalendarDays, Keyboard, X, Check, Folder, BriefcaseBusiness, Layers3, Trash2} from 'lucide-react';
import './styles.css';
import './settings.css';
import './presets.css';
import './visual-overrides.css';
import './product-overrides.css';

type Site={title:string; desc:string; domain:string; color:string; icon:string; category:string; favorite?:boolean; badge?:string};
const initialSites:Site[]=[
 {title:'Figma',desc:'Дизайн и прототипирование',domain:'figma.com',color:'#f24e35',icon:'F',category:'Проект',favorite:true},
 {title:'Notion',desc:'Рабочее пространство',domain:'notion.so',color:'#191919',icon:'N',category:'Работа',favorite:true},
 {title:'YouTube',desc:'Видео и музыка',domain:'youtube.com',color:'#ff0033',icon:'▶',category:'Развлечения',badge:'3'},
 {title:'GitHub',desc:'Репозитории и код',domain:'github.com',color:'#24292f',icon:'◉',category:'Работа'},
 {title:'Google Drive',desc:'Файлы и документы',domain:'drive.google.com',color:'#4285f4',icon:'△',category:'Работа'},
 {title:'Telegram',desc:'Мессенджер',domain:'telegram.org',color:'#229ed9',icon:'➤',category:'Личное',badge:'12'},
 {title:'ChatGPT',desc:'Ваш AI-помощник',domain:'chatgpt.com',color:'#16a085',icon:'✳',category:'Работа'},
 {title:'Spotify',desc:'Музыка для работы',domain:'spotify.com',color:'#1ed760',icon:'◔',category:'Развлечения'},
 {title:'Dribbble',desc:'Вдохновение для дизайна',domain:'dribbble.com',color:'#ea4c89',icon:'●',category:'Вдохновение'},
 {title:'Яндекс',desc:'Поиск в интернете',domain:'yandex.ru',color:'#fc3f1d',icon:'Я',category:'Личное'},
 {title:'Мой календарь',desc:'Встречи и события',domain:'calendar.google.com',color:'#4285f4',icon:'31',category:'Работа'},
 {title:'Почта',desc:'Входящие сообщения',domain:'mail.google.com',color:'#e94235',icon:'✉',category:'Личное',badge:'5'}
];
const nav=[['Быстрый доступ',Home],['Избранное',Heart],['Недавние',Clock3],['Загрузки',Download],['Заметки',StickyNote],['Настройки',SettingsIcon]] as const;
function App(){
 const [sites,setSites]=useState<Site[]>(()=>{try{return JSON.parse(localStorage.getItem('nexus-sites')||'null')||initialSites}catch{return initialSites}}); const [active,setActive]=useState('Быстрый доступ'); const [query,setQuery]=useState(''); const [calendar,setCalendar]=useState(false); const [settings,setSettings]=useState(false); const [addOpen,setAddOpen]=useState(false); const [mobileNav,setMobileNav]=useState(false); const [view,setView]=useState<'grid'|'list'>('grid'); const [density,setDensity]=useState(()=>Number(localStorage.getItem('nexus-density')||20)); const [selected,setSelected]=useState<string|null>(null); const [toast,setToast]=useState('');
 const date=new Date(); const time=date.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}); const weekday=date.toLocaleDateString('ru-RU',{weekday:'long'}); const dateText=date.toLocaleDateString('ru-RU',{day:'numeric',month:'long'});
 useEffect(()=>{localStorage.setItem('nexus-sites',JSON.stringify(sites))},[sites]); useEffect(()=>{localStorage.setItem('nexus-density',String(density))},[density]); useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(t)},[toast]);
 const filtered=useMemo(()=>sites.filter(s=>(active==='Избранное'?s.favorite:true)&&(`${s.title} ${s.desc} ${s.domain}`.toLowerCase().includes(query.toLowerCase()))).slice(active==='Недавние'?0:undefined,active==='Недавние'?6:undefined),[sites,active,query]);
 const toggleFav=(title:string)=>setSites(x=>x.map(s=>s.title===title?{...s,favorite:!s.favorite}:s));
 return <div className="app">
  <aside className="sidebar glass">
   <div className="brand"><div className="brand-mark"><span></span><span></span><span></span></div><div><strong>NEXUS</strong><small>Speed Dial</small></div></div>
   <button className="date-button" onClick={()=>setCalendar(v=>!v)} aria-label="Открыть календарь"><div className="clock">{time}</div><div className="date-line"><span>{weekday}, {dateText}</span><CalendarDays size={15}/></div></button>
   {calendar&&<Calendar onClose={()=>setCalendar(false)}/>} 
   <div className="weather"><div className="weather-icon"><CloudSun size={27}/></div><div><b>+18°</b><span>Переменная облачность</span></div><strong>Москва</strong></div>
   <div className="side-section"><div className="section-label">ПРОЕКТЫ <Plus size={15}/></div><div className="project active"><span className="dot blue"></span>Дом <span className="count">8</span></div><div className="project"><BriefcaseBusiness size={15}/>Работа <span className="count">14</span></div><div className="project"><Layers3 size={15}/>Проект <span className="count">6</span></div></div>
   <div className="side-section categories"><div className="section-label">КАТЕГОРИИ <Plus size={15}/></div><div className="chips"><span className="chip blue-chip">Все <b>28</b></span><span className="chip">Работа <b>9</b></span><span className="chip">Личное <b>7</b></span><span className="chip">Развлечения <b>6</b></span><span className="chip">Вдохновение <b>6</b></span></div></div>
   <div className="side-footer"><div className="storage"><div><span>Хранилище</span><b>28 из 100</b></div><div className="progress"><i></i></div></div><div className="profile"><div className="avatar">АК</div><div><b>Алексей К.</b><span>Личный профиль</span></div><MoreHorizontal size={19}/></div></div>
  </aside>
  <main className="main">
   <header className="topbar"><button className="mobile-sections" onClick={()=>setMobileNav(true)} aria-label="Разделы"><Layers3 size={18}/></button><div className="history"><button><ChevronLeft size={18}/></button><button><ChevronRight size={18}/></button></div><div className="omnibox"><Search size={18}/><input placeholder="Введите запрос или адрес" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><button className="top-icon"><Star size={18}/></button><button className="top-icon"><ShieldCheck size={18}/></button><div className="mini-avatar">АК</div></header>
   <div className="workspace-head"><div><h1>{active}</h1><p>{active==='Быстрый доступ'?'Ваши любимые сайты в одном месте':active==='Избранное'?'Сайты, которые вы отметили звездой':'Ваша подборка сайтов'}</p></div><button className="add-button" onClick={()=>setAddOpen(true)}><Plus size={18}/> Добавить сайт</button></div>
   <div className="toolbar"><div className="tabs"><button className={active==='Быстрый доступ'?'selected':''} onClick={()=>setActive('Быстрый доступ')}>Все сайты <b>{sites.length}</b></button><button className={active==='Избранное'?'selected':''} onClick={()=>setActive('Избранное')}>Избранное <b>{sites.filter(s=>s.favorite).length}</b></button><button>Недавние</button></div><div className="tools"><button className={view==='grid'?'on':''} onClick={()=>setView('grid')}><Grid2X2 size={17}/></button><button className={view==='list'?'on':''} onClick={()=>setView('list')}><List size={18}/></button><span className="divider"></span><button onClick={()=>setSettings(true)}><SlidersHorizontal size={17}/> Вид</button><button><MoreHorizontal size={18}/></button></div></div>
   {filtered.length?<div className={'site-grid '+(view==='list'?'list-view':'')} style={{gap:density}}>{filtered.map(site=><SiteTile key={site.title} site={site} selected={selected===site.title} onSelect={()=>setSelected(site.title)} onFav={()=>toggleFav(site.title)} onToast={setToast}/>)}</div>:<div className="empty"><Search size={30}/><b>Ничего не найдено</b><span>Попробуйте изменить запрос</span></div>}
  </main>
  <nav className="dock glass">{nav.map(([label,Icon])=><button key={label} className={active===label?'dock-active':''} onClick={()=>label==='Настройки'?setSettings(true):setActive(label)}><Icon size={19}/><span>{label}</span></button>)}</nav>
  {settings&&<Settings onClose={()=>setSettings(false)} density={density} setDensity={setDensity}/>} {addOpen&&<AddSiteModal onClose={()=>setAddOpen(false)} onSave={site=>{setSites(x=>[site,...x]);setAddOpen(false);setToast('Сайт добавлен')}}/>} {mobileNav&&<MobileSections active={active} setActive={setActive} onClose={()=>setMobileNav(false)}/>} {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}
function SiteTile({site,selected,onSelect,onFav,onToast}:{site:Site;selected:boolean;onSelect:()=>void;onFav:()=>void;onToast:(x:string)=>void}){return <article className={'site-card glass '+(selected?'is-selected':'')} onClick={onSelect} onDoubleClick={()=>{window.open('https://'+site.domain,'_blank','noopener,noreferrer');onToast(`Открыт ${site.title}`)}}><div className="card-top"><div className="site-icon" style={{background:site.color}}>{site.icon}</div><button className={'star '+(site.favorite?'fav':'')} onClick={e=>{e.stopPropagation();onFav()}}><Star size={16} fill={site.favorite?'currentColor':'none'}/></button></div><div className="site-copy"><h3>{site.title}</h3><p>{site.desc}</p><span>{site.domain}</span></div>{site.badge&&<em className="badge">{site.badge}</em>}<button className="card-more" onClick={e=>{e.stopPropagation();onToast('Действия с сайтом')}}><MoreHorizontal size={17}/></button></article>}
function AddSiteModal({onClose,onSave}:{onClose:()=>void;onSave:(site:Site)=>void}){const [title,setTitle]=useState('');const [domain,setDomain]=useState('');const [desc,setDesc]=useState('');const [color,setColor]=useState('#2f7cf6');const submit=(e:React.FormEvent)=>{e.preventDefault();const clean=domain.replace(/^https?:\/\//,'').split('/')[0];if(!title.trim()||!clean)return;onSave({title:title.trim(),domain:clean,desc:desc.trim()||'Сохранённый сайт',color,icon:title.trim()[0].toUpperCase(),category:'Личное'})};return <div className="overlay"><form className="site-form glass" onSubmit={submit}><header><div><span className="eyebrow">БЫСТРЫЙ ДОСТУП</span><h2>Добавить сайт</h2><p>Сохраните любимый сайт в одну плитку</p></div><button type="button" className="close" onClick={onClose}><X/></button></header><label>Название<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Например, Linear"/></label><label>Адрес сайта<input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="linear.app"/></label><label>Описание<input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Короткое описание"/></label><label>Цвет иконки<div className="form-colors">{['#2f7cf6','#885cf6','#e95674','#ef9e35','#22a87c','#1c9dbb'].map(c=><button type="button" key={c} className={color===c?'active':''} style={{background:c}} onClick={()=>setColor(c)}/>)}</div></label><footer><button type="button" className="reset" onClick={onClose}>Отмена</button><button className="save" type="submit" disabled={!title.trim()||!domain.trim()}>Добавить сайт</button></footer></form></div>}
function MobileSections({active,setActive,onClose}:{active:string;setActive:(s:string)=>void;onClose:()=>void}){return <div className="overlay mobile-sheet"><section className="mobile-sections-card glass"><header><b>Разделы и проекты</b><button onClick={onClose}><X/></button></header>{nav.map(([label,Icon])=><button className={active===label?'active':''} key={label} onClick={()=>{setActive(label);onClose()}}><Icon size={18}/>{label}<ChevronRight size={15}/></button>)}</section></div>}
function Calendar({onClose}:{onClose:()=>void}){const [cursor,setCursor]=useState(new Date());const [selected,setSelected]=useState(new Date());const year=cursor.getFullYear(),month=cursor.getMonth(),first=new Date(year,month,1).getDay()||7,last=new Date(year,month+1,0).getDate();const monthName=cursor.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});const days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];return <div className="calendar glass" role="dialog" aria-label="Календарь"><div className="cal-head"><div><b>{monthName[0].toUpperCase()+monthName.slice(1)}</b><span>{selected.toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</span></div><div><button aria-label="Предыдущий месяц" onClick={()=>setCursor(new Date(year,month-1,1))}><ChevronLeft size={16}/></button><button aria-label="Следующий месяц" onClick={()=>setCursor(new Date(year,month+1,1))}><ChevronRight size={16}/></button></div></div><div className="week">{days.map(x=><span key={x}>{x}</span>)}</div><div className="days">{Array.from({length:first-1},(_,i)=><i key={'empty'+i}/>)}{Array.from({length:last},(_,i)=>{const day=i+1;const active=selected.getFullYear()===year&&selected.getMonth()===month&&selected.getDate()===day;return <button className={active?'today':''} key={day} onClick={()=>setSelected(new Date(year,month,day))}>{day}</button>})}</div><div className="cal-note"><div className="note-dot"></div><span><b>{selected.getDate()===new Date().getDate()&&selected.getMonth()===new Date().getMonth()?'Сегодня':'Выбранный день'}</b><small>Нет запланированных событий</small></span><ChevronRight size={16}/></div><button className="close-cal" onClick={onClose}><X size={14}/></button></div>}
function Settings({onClose,density,setDensity}:{onClose:()=>void;density:number;setDensity:(x:number)=>void}){
 const [section,setSection]=useState('Общие');
 const [saved,setSaved]=useState(()=>localStorage.getItem('nexus-settings')==='1');
 const [compact,setCompact]=useState(false); const [animations,setAnimations]=useState(true); const [sidebar,setSidebar]=useState(true); const [weather,setWeather]=useState(true); const [newTab,setNewTab]=useState(true);
 const sections=[['Общие','Настройки приложения'],['Оформление','Цвета и тема'],['Плитки сайтов','Сетка и карточки'],['Боковая панель','Навигация'],['Поиск','Омнибокс и подсказки'],['Погода и дата','Виджеты'],['Данные','Импорт и экспорт'],['Приватность','Безопасность'],['Горячие клавиши','Быстрые действия']];
 const toggleSave=()=>{localStorage.setItem('nexus-settings','1');setSaved(true)};
 return <div className="overlay"><section className="settings-page glass">
  <header className="settings-header"><div className="settings-title"><button className="back-settings" onClick={onClose}><ChevronLeft size={17}/></button><div><span className="eyebrow">NEXUS / ПАРАМЕТРЫ</span><h2>Настройки приложения</h2></div></div><div className="settings-actions">{saved&&<span className="saved-state"><Check size={14}/> Сохранено</span>}<button className="close" onClick={onClose}><X/></button></div></header>
  <div className="settings-layout"><aside className="settings-nav"><span className="nav-caption">РАЗДЕЛЫ</span>{sections.map(([name,desc],i)=><button key={name} className={section===name?'active':''} onClick={()=>setSection(name)}><span className="setting-nav-icon">{['⚙','◐','▦','☷','⌕','☼','↕','◉','⌨'][i]}</span><span><b>{name}</b><small>{desc}</small></span>{name==='Плитки сайтов'&&<em>NEW</em>}</button>)}<div className="settings-version"><span className="brand-dot"></span><div><b>Nexus Speed Dial</b><small>Версия 1.0.0 · Лицензия MIT</small></div></div></aside>
  <div className="settings-content"><div className="settings-content-head"><div><h3>{section}</h3><p>{sections.find(x=>x[0]===section)?.[1]}</p></div><button className="reset" onClick={()=>{setDensity(20);setCompact(false);setAnimations(true)}}>Сбросить раздел</button></div>
   {section==='Общие'&&<General compact={compact} setCompact={setCompact} animations={animations} setAnimations={setAnimations} newTab={newTab} setNewTab={setNewTab}/>} 
   {section==='Оформление'&&<Appearance/>}
   {section==='Плитки сайтов'&&<TileAppearance density={density} setDensity={setDensity}/>} 
   {section==='Боковая панель'&&<SidebarSettings sidebar={sidebar} setSidebar={setSidebar} weather={weather} setWeather={setWeather}/>} 
   {section==='Поиск'&&<SearchSettings/>}
   {section==='Погода и дата'&&<WeatherSettings/>}
   {section==='Данные'&&<DataSettings/>}
   {section==='Приватность'&&<PrivacySettings/>}
   {section==='Горячие клавиши'&&<Shortcuts/>}
  </div></div><footer className="settings-footer"><span>Изменения применяются автоматически</span><button className="save" onClick={toggleSave}>Сохранить изменения</button></footer>
 </section></div>
}
function SettingRow({title,desc,children}:{title:string;desc:string;children:React.ReactNode}){return <div className="setting-row"><div><b>{title}</b><small>{desc}</small></div>{children}</div>}
function Switch({value,onChange}:{value:boolean;onChange:(v:boolean)=>void}){const [local,setLocal]=useState(value);useEffect(()=>setLocal(value),[value]);return <input aria-label="Переключатель" type="checkbox" checked={local} onChange={e=>{setLocal(e.target.checked);onChange(e.target.checked)}}/>}
function General({compact,setCompact,animations,setAnimations,newTab,setNewTab}:{compact:boolean;setCompact:(v:boolean)=>void;animations:boolean;setAnimations:(v:boolean)=>void;newTab:boolean;setNewTab:(v:boolean)=>void}){return <div className="settings-stack"><div className="settings-card"><h4>Основные параметры</h4><SettingRow title="Открывать Nexus в новой вкладке" desc="Показывать быстрый доступ при запуске новой вкладки"><Switch value={newTab} onChange={setNewTab}/></SettingRow><SettingRow title="Компактный интерфейс" desc="Уменьшить отступы и размеры элементов интерфейса"><Switch value={compact} onChange={setCompact}/></SettingRow><SettingRow title="Плавные анимации" desc="Анимация наведения, переходов и открытия окон"><Switch value={animations} onChange={setAnimations}/></SettingRow></div><div className="settings-card"><h4>Язык и регион</h4><div className="select-row"><span>Язык приложения</span><button>Русский <ChevronRight size={15}/></button></div><div className="select-row"><span>Формат даты</span><button>16 сентября 2026 <ChevronRight size={15}/></button></div></div></div>}
function Appearance(){
 const [theme,setTheme]=useState(()=>localStorage.getItem('nexus-theme')||'light'); const [accent,setAccent]=useState(()=>localStorage.getItem('nexus-accent')||'#2f7cf6'); const [wall,setWall]=useState(()=>localStorage.getItem('nexus-wallpaper')||'aurora');
 useEffect(()=>{localStorage.setItem('nexus-theme',theme);localStorage.setItem('nexus-accent',accent);localStorage.setItem('nexus-wallpaper',wall);document.documentElement.style.setProperty('--accent',accent);document.documentElement.dataset.theme=theme;document.documentElement.style.setProperty('--app-wallpaper',wall==='aurora'?'radial-gradient(circle at 70% 0%,#dcecff 0,#f5f9fd 42%,#e9f1fa 100%)':wall==='warm'?'radial-gradient(circle at 25% 0%,#fff2df,#f7f4ef 50%,#eaf0f8)':wall==='mint'?'radial-gradient(circle at 80% 10%,#dff8f0,#f4fbfa 45%,#ebf3fa)':'#eef4fb')},[theme,accent,wall]);
 return <div className="settings-stack"><div className="settings-card"><h4>Тема оформления</h4><div className="theme-options"><button className={'theme-choice '+(theme==='light'?'selected':'')} onClick={()=>setTheme('light')}><i className="theme-swatch light"></i><b>Светлая</b><small>Чистая и воздушная</small>{theme==='light'&&<Check size={15}/>}</button><button className={'theme-choice '+(theme==='dark'?'selected':'')} onClick={()=>setTheme('dark')}><i className="theme-swatch dark"></i><b>Тёмная</b><small>Для комфортной работы</small>{theme==='dark'&&<Check size={15}/>}</button><button className={'theme-choice '+(theme==='system'?'selected':'')} onClick={()=>setTheme('system')}><i className="theme-swatch system"></i><b>Системная</b><small>Следовать настройкам ОС</small>{theme==='system'&&<Check size={15}/>}</button></div></div><div className="settings-card"><h4>Акцентный цвет</h4><div className="colors">{['#2f7cf6','#885cf6','#e95674','#ef9e35','#22a87c','#1c9dbb'].map(c=><button key={c} aria-label={'Акцент '+c} onClick={()=>setAccent(c)} className={'color '+(accent===c?'active':'')} style={{background:c}}></button>)}</div></div><div className="settings-card"><div className="card-heading"><h4>Обои рабочего пространства</h4><span className="live-label">LIVE</span></div><div className="wallpapers"><button className={wall==='aurora'?'active':''} onClick={()=>setWall('aurora')} style={{background:'radial-gradient(circle at 70% 0%,#dcecff,#f5f9fd 55%,#e9f1fa)'}}></button><button className={wall==='warm'?'active':''} onClick={()=>setWall('warm')} style={{background:'radial-gradient(circle at 25% 0%,#fff2df,#f7f4ef 50%,#eaf0f8)'}}></button><button className={wall==='mint'?'active':''} onClick={()=>setWall('mint')} style={{background:'radial-gradient(circle at 80% 10%,#dff8f0,#f4fbfa 45%,#ebf3fa)'}}></button><button className={wall==='plain'?'active':''} onClick={()=>setWall('plain')} style={{background:'#eef4fb'}}></button></div><small className="field-hint">Обои применяются ко всем разделам, а не только к главной странице.</small></div></div>}
function TileAppearance({density,setDensity}:{density:number;setDensity:(v:number)=>void}){
 const [mode,setMode]=useState('standard'); const [preset,setPreset]=useState('glass'); const presets=[['soft','Soft'],['compact','Compact'],['flat','Flat'],['neon','Neon'],['glass','Glass'],['neumorphic','Neumorphic'],['layered','Layered'],['aurora','Aurora'],['elevated','Elevated']];
 useEffect(()=>{document.documentElement.dataset.tilePreset=preset;document.documentElement.dataset.tileMode=mode},[preset,mode]);
 return <div className="settings-stack"><div className="settings-card"><div className="card-heading"><h4>Режим отображения</h4><span className="live-label">● LIVE</span></div><div className="mode-grid">{[['standard','Стандарт'],['icon','Только иконки'],['list','Список'],['preview','Превью'],['screenshot','Скриншот'],['ios','iOS']].map(([id,label])=><button key={id} className={mode===id?'active':''} onClick={()=>setMode(id)}><span>{id==='icon'?'◈':id==='list'?'☷':id==='preview'?'▧':id==='screenshot'?'▣':id==='ios'?'⌘':'▦'}</span>{label}</button>)}</div></div><div className="settings-card"><h4>Визуальный пресет</h4><p className="card-text">Готовые сочетания теней, фона, скругления и hover-эффектов.</p><div className="preset-grid">{presets.map(([id,label])=><button key={id} className={'preset-option preset-'+id+(preset===id?' active':'')} onClick={()=>{setPreset(id);setDensity(id==='compact'?12:id==='neumorphic'?24:20)}}><i></i><b>{label}</b>{preset===id&&<Check size={13}/>}</button>)}</div></div><div className="settings-card"><h4>Сетка быстрого доступа</h4><SettingRow title="Плотность плиток" desc="Расстояние между карточками в сетке"><div className="range-control"><output>{density}px</output><input aria-label="Плотность плиток" type="range" min="4" max="32" value={density} onChange={e=>setDensity(+e.target.value)}/></div></SettingRow><SettingRow title="Размер плиток" desc="Базовый размер карточек сайта"><div className="segmented"><button>S</button><button className="active">M</button><button>L</button><button>XL</button></div></SettingRow><SettingRow title="Скругление углов" desc="Радиус углов карточек"><div className="segmented wide"><button>12</button><button className="active">20</button><button>28</button></div></SettingRow></div><div className="settings-card"><h4>Содержимое плиток</h4><SettingRow title="Описание сайта" desc="Показывать короткое описание под названием"><Switch value={true} onChange={()=>{}}/></SettingRow><SettingRow title="Домен сайта" desc="Показывать адрес в нижней части плитки"><Switch value={true} onChange={()=>{}}/></SettingRow><SettingRow title="Счётчики уведомлений" desc="Показывать новые сообщения и события"><Switch value={true} onChange={()=>{}}/></SettingRow></div></div>}
function SidebarSettings({sidebar,setSidebar,weather,setWeather}:{sidebar:boolean;setSidebar:(v:boolean)=>void;weather:boolean;setWeather:(v:boolean)=>void}){return <div className="settings-stack"><div className="settings-card"><h4>Элементы боковой панели</h4><SettingRow title="Боковая панель" desc="Закрепить навигацию слева на рабочем столе"><Switch value={sidebar} onChange={setSidebar}/></SettingRow><SettingRow title="Погода" desc="Текущая температура и прогноз на день"><Switch value={weather} onChange={setWeather}/></SettingRow><SettingRow title="Проекты" desc="Группы сайтов для разных задач"><Switch value={true} onChange={()=>{}}/></SettingRow></div><div className="settings-card"><h4>Поведение</h4><div className="select-row"><span>Ширина панели</span><button>292 px <ChevronRight size={15}/></button></div><div className="select-row"><span>Показывать на мобильных</span><button>В виде меню <ChevronRight size={15}/></button></div></div></div>}
function SearchSettings(){return <div className="settings-stack"><div className="settings-card"><h4>Строка поиска</h4><SettingRow title="Поиск по сайтам" desc="Искать среди сохранённых плиток при вводе"><Switch value={true} onChange={()=>{}}/></SettingRow><SettingRow title="Поисковые подсказки" desc="Показывать подсказки поисковой системы"><Switch value={true} onChange={()=>{}}/></SettingRow><div className="select-row"><span>Поисковая система</span><button>Google <ChevronRight size={15}/></button></div></div><div className="info-box"><Search size={18}/><span>Совет: нажмите <kbd>⌘ K</kbd>, чтобы быстро перейти к строке поиска.</span></div></div>}
function WeatherSettings(){return <div className="settings-stack"><div className="settings-card"><h4>Погода и дата</h4><div className="select-row"><span>Город</span><button>Москва <ChevronRight size={15}/></button></div><div className="select-row"><span>Единицы температуры</span><button>Цельсий (°C) <ChevronRight size={15}/></button></div><SettingRow title="Автоматическое обновление" desc="Обновлять погоду каждые 30 минут"><Switch value={true} onChange={()=>{}}/></SettingRow></div><div className="info-box"><CloudSun size={18}/><span>Погода использует открытые данные и не требует доступа к геолокации.</span></div></div>}
function DataSettings(){return <div className="settings-stack"><div className="settings-card"><h4>Резервная копия</h4><p className="card-text">Сохраните плитки, проекты, категории и настройки в один файл.</p><div className="data-buttons"><button className="outline"><Download size={15}/> Экспортировать данные</button><button className="outline"><ExternalLink size={15}/> Импортировать данные</button></div></div><div className="settings-card danger-card"><h4>Опасная зона</h4><p className="card-text">Удалить все сохранённые сайты и вернуть настройки по умолчанию.</p><button className="danger"><Trash2 size={15}/> Очистить все данные</button></div></div>}
function PrivacySettings(){return <div className="settings-stack"><div className="settings-card"><h4>Приватность</h4><SettingRow title="Локальное хранение" desc="Данные остаются только на этом устройстве"><Switch value={true} onChange={()=>{}}/></SettingRow><SettingRow title="История открытий" desc="Сохранять недавно открытые сайты"><Switch value={true} onChange={()=>{}}/></SettingRow><SettingRow title="Анонимная статистика" desc="Помогать улучшать Nexus без личных данных"><Switch value={false} onChange={()=>{}}/></SettingRow></div><div className="info-box"><ShieldCheck size={18}/><span>Ваши данные не отправляются на сервер. Синхронизация отключена.</span></div></div>}
function Shortcuts(){const keys=[['⌘ K','Фокус на поиск'],['⌘ N','Добавить новый сайт'],['⌘ B','Открыть избранное'],['⌘ ,','Открыть настройки'],['Esc','Закрыть окно или поиск']];return <div className="settings-stack"><div className="settings-card shortcut-card">{keys.map(([key,label])=><div className="shortcut" key={key}><span>{label}</span><kbd>{key}</kbd></div>)}</div><div className="info-box"><Keyboard size={18}/><span>Сочетания можно изменить в будущей версии.</span></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
