import React, {useEffect, useMemo, useReducer, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, ChevronLeft, ChevronRight, Star, ShieldCheck, UserRound, CloudSun, Plus, Home, Heart, Clock3, Download, StickyNote, Settings as SettingsIcon, Grid2X2, List, SlidersHorizontal, MoreHorizontal, ExternalLink, CalendarDays, Keyboard, X, Check, Folder, BriefcaseBusiness, Layers3, Trash2, Pencil, Upload, FileJson} from 'lucide-react';
import './styles.css';
import './settings.css';
import './presets.css';
import './visual-overrides.css';
import './product-overrides.css';
import './actions.css';
import './form-controls.css';
import { readStorage, writeStorage } from './domain/storage';
import { filterSites, reorderSites } from './domain/siteUtils';
import type { SiteRecord as Site, TileMode, VisualPreset } from './domain/types';
import type { AppearanceState } from './domain/appStore';
import { NotesWorkspace } from './components/NotesWorkspace';
import { CalendarPopover } from './components/CalendarPopover';
import { SiteTile } from './components/SiteTile';
import { AddSiteModal } from './components/AddSiteModal';
import { MobileSections } from './components/MobileSections';
import { Settings } from './components/SettingsPanel';
import { applyTileStyle } from './domain/tileStyleBridge';
import { appReducer, createInitialAppState, persistAppState } from './domain/appStore';

const initialSites:Site[]=[
 {title:'Figma',desc:'Дизайн и прототипирование',domain:'figma.com',color:'#f24e35',icon:'F',category:'Проект',favorite:true},
 {title:'Notion',desc:'Рабочее пространство',domain:'notion.so',color:'#191919',icon:'N',category:'Работа',favorite:true},
 {title:'YouTube',desc:'Видео и музыка',domain:'youtube.com',color:'#ff0033',icon:'▶',category:'Развлечения',badge:'3'},
 {title:'GitHub',desc:'Репозитории и код',domain:'github.com',color:'#24292f',icon:'◉',category:'Работа'},
 {title:'Google Drive',desc:'Файлы и документы',domain:'drive.google.com',color:'#4285f4',icon:'△',category:'Работа'},
 {title:'Telegram',desc:'Мессенджер',domain:'telegram.org',color:'#229ed9',icon:'➤',category:'Личное',badge:'12'},
 {title:'ChatGPT',desc:'Ваш AI-помощник',domain:'chatgpt.com',color:'#16a085',icon:'✳',category:'Работа'},
 {title:'Spotify',desc:'Музыка для работы',domain:'spotify.com',color:'#1ed760',icon:'◔',category:'Развлечения'},
 {title:'Dribbble',desc:'Вдохновение для дизайна',domain:'dribbble.com',color:'#ea4c89',icon:'●',category:'Вдохновение'},
 {title:'Яндекс',desc:'Поиск в интернете',domain:'yandex.ru',color:'#fc3f1d',icon:'Я',category:'Личное'},
 {title:'Мой календарь',desc:'Встречи и события',domain:'calendar.google.com',color:'#4285f4',icon:'31',category:'Работа'},
 {title:'Почта',desc:'Входящие сообщения',domain:'mail.google.com',color:'#e94235',icon:'✉',category:'Личное',badge:'5'}
];
const nav=[['Быстрый доступ',Home],['Избранное',Heart],['Недавние',Clock3],['Загрузки',Download],['Заметки',StickyNote],['Настройки',SettingsIcon]] as const;
function App(){
 const [appState,dispatch]=useReducer(appReducer,initialSites,createInitialAppState); const {sites,categories,history,density,ui,tile,appearance}=appState; const setSites=(value:Site[]|((current:Site[])=>Site[]))=>dispatch({type:'sites/set',value}); const setCategories=(value:string[]|((current:string[])=>string[]))=>dispatch({type:'categories/set',value}); const setHistory=(value:string[]|((current:string[])=>string[]))=>dispatch({type:'history/set',value}); const setDensity=(value:number)=>dispatch({type:'density/set',value}); const setAppearance=(value:AppearanceState|((current:AppearanceState)=>AppearanceState))=>dispatch({type:'appearance/set',value}); const setTile=(value:typeof tile|((current:typeof tile)=>typeof tile))=>dispatch({type:'tile/set',value}); const setUi=(value:typeof ui|((current:typeof ui)=>typeof ui))=>dispatch({type:'ui/set',value}); const [active,setActive]=useState('Быстрый доступ'); const [activeCategory,setActiveCategory]=useState('Все'); const [query,setQuery]=useState(''); const [calendar,setCalendar]=useState(false); const [settings,setSettings]=useState(false); const [addOpen,setAddOpen]=useState(false); const [mobileNav,setMobileNav]=useState(false); const [view,setView]=useState<'grid'|'list'>('grid'); const [selected,setSelected]=useState<string|null>(null); const [multiSelect,setMultiSelect]=useState(false); const [selectedMany,setSelectedMany]=useState<string[]>([]); const [dragged,setDragged]=useState<string|null>(null); const [editing,setEditing]=useState<Site|null>(null); const [toast,setToast]=useState(''); const [weatherData,setWeatherData]=useState({temp:'18°',label:'Переменная облачность',city:'Москва'});
 const date=new Date(); const time=date.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}); const weekday=date.toLocaleDateString('ru-RU',{weekday:'long'}); const dateText=date.toLocaleDateString('ru-RU',{day:'numeric',month:'long'}); useEffect(()=>{persistAppState(appState);applyTileStyle({...tile,density});document.documentElement.dataset.theme=appearance.theme;document.documentElement.style.setProperty('--accent',appearance.accent);document.documentElement.style.setProperty('--app-wallpaper',appearance.wallpaper==='aurora'?'radial-gradient(circle at 70% 0%,#dcecff 0,#f5f9fd 42%,#e9f1fa 100%)':appearance.wallpaper==='warm'?'radial-gradient(circle at 25% 0%,#fff2df,#f7f4ef 50%,#eaf0f8)':appearance.wallpaper==='mint'?'radial-gradient(circle at 80% 10%,#dff8f0,#f4fbfa 45%,#ebf3fa)':'#eef4fb')},[appState,tile,density,appearance]);
 useEffect(()=>{const locations:Record<string,[number,number]>={'Москва':[55.75,37.62],'Санкт-Петербург':[59.93,30.31],'Берлин':[52.52,13.4],'Лондон':[51.51,-0.13]};const [latitude,longitude]=locations[ui.weatherCity]||locations['Москва'];const unit=ui.weatherUnits==='Фаренгейт (°F)'?'&temperature_unit=fahrenheit':'';fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&timezone=auto${unit}`).then(r=>r.json()).then(d=>{const code=d.current?.weather_code;const labels:Record<number,string>={0:'Ясно',1:'Преимущественно ясно',2:'Переменная облачность',3:'Пасмурно',61:'Небольшой дождь',63:'Дождь',71:'Снег'};if(d.current?.temperature_2m!=null)setWeatherData({temp:Math.round(d.current.temperature_2m)+'°',label:labels[code]||'Переменная облачность',city:ui.weatherCity})}).catch(()=>setWeatherData(x=>({...x,city:ui.weatherCity})));},[ui.weatherCity,ui.weatherUnits]); useEffect(()=>{writeStorage('nexus-sites',sites);writeStorage('nexus-categories',categories)},[sites,categories]); useEffect(()=>{writeStorage('nexus-density',density);writeStorage('nexus-history',history)},[density,history]); useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector<HTMLInputElement>('.omnibox input')?.focus()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='n'){e.preventDefault();setAddOpen(true)}if(e.key==='Escape'){setCalendar(false);setSettings(false);setAddOpen(false);setEditing(null);setMobileNav(false)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]); useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(t)},[toast]);
 const filtered=useMemo(()=>filterSites(sites,query,activeCategory,active),[sites,active,activeCategory,query]);
 const reorder=(target:string)=>{if(!dragged||dragged===target)return;setSites(items=>reorderSites(items,dragged,target));}; const toggleFav=(title:string)=>setSites(x=>x.map(s=>s.title===title?{...s,favorite:!s.favorite}:s));
 return <div className={'app '+(ui.compact?'compact-ui':'')+(ui.animations?'':' reduced-motion')} style={{'--sidebar-width':ui.sidebarWidth||'292 px'} as React.CSSProperties}>{ui.sidebar&&<aside className="sidebar glass">
   <div className="brand"><div className="brand-mark"><span></span><span></span><span></span></div><div><strong>NEXUS</strong><small>Speed Dial</small></div></div>
   <button className="date-button" onClick={()=>setCalendar(v=>!v)} aria-label="Открыть календарь"><div className="clock">{time}</div><div className="date-line"><span>{weekday}, {dateText}</span><CalendarDays size={15}/></div></button>
   {calendar&&<CalendarPopover onClose={()=>setCalendar(false)}/>} 
   {ui.weather&&<div className="weather"><div className="weather-icon"><CloudSun size={27}/></div><div><b>{weatherData.temp}</b><span>{weatherData.label}</span></div><strong>{weatherData.city}</strong></div>}
   {ui.projects!==false&&<div className="side-section"><div className="section-label">ПРОЕКТЫ <Plus size={15}/></div><div className="project active"><span className="dot blue"></span>Дом <span className="count">8</span></div><div className="project"><BriefcaseBusiness size={15}/>Работа <span className="count">14</span></div><div className="project"><Layers3 size={15}/>Проект <span className="count">6</span></div></div>}
   <div className="side-section categories"><div className="section-label">КАТЕГОРИИ <button aria-label="Добавить категорию" onClick={()=>{const name=prompt("Название новой категории");if(name?.trim()&&!categories.includes(name.trim()))setCategories(x=>[...x,name.trim()])}}><Plus size={15}/></button></div><div className="chips">{[["Все",sites.length],...categories.map(name=>[name,sites.filter(s=>s.category===name).length] as [string,number])].map(([name,count])=><button key={name} className={"chip "+(activeCategory===name?"blue-chip":"")} onClick={()=>setActiveCategory(name as string)} onDoubleClick={()=>{if(name!=="Все"){const renamed=prompt("Переименовать категорию",String(name));if(renamed?.trim()&&renamed.trim()!==name){setCategories(x=>x.map(c=>c===name?renamed.trim():c));setSites(x=>x.map(item=>item.category===name?{...item,category:renamed.trim()}:item));if(activeCategory===name)setActiveCategory(renamed.trim())}}}}>{name} <b>{count}</b></button>)}</div></div>
   <div className="side-footer"><div className="storage"><div><span>Хранилище</span><b>28 из 100</b></div><div className="progress"><i></i></div></div><div className="profile"><div className="avatar">АК</div><div><b>Алексей К.</b><span>Личный профиль</span></div><MoreHorizontal size={19}/></div></div>
  </aside>}
  <main className="main">
   <header className="topbar"><button className="mobile-sections" onClick={()=>setMobileNav(true)} aria-label="Разделы"><Layers3 size={18}/></button><div className="history"><button aria-label="Назад" onClick={()=>window.history.back()}><ChevronLeft size={18}/></button><button aria-label="Вперёд" onClick={()=>window.history.forward()}><ChevronRight size={18}/></button></div><div className="omnibox"><Search size={18}/><input placeholder="Введите запрос или адрес" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&query.trim()){const value=query.trim();window.open(/^https?:\/\//.test(value)?value:'https://www.google.com/search?q='+encodeURIComponent(value),'_blank','noopener,noreferrer');setHistory(x=>[value,...x.filter(n=>n!==value)].slice(0,20))}}}/><kbd>⌘ K</kbd></div><button className="top-icon" aria-label="Избранное" onClick={()=>setActive('Избранное')}><Star size={18}/></button><button className="top-icon" aria-label="Безопасность"><ShieldCheck size={18}/></button><div className="mini-avatar">АК</div></header>
   <div className="workspace-head"><div><h1>{active}</h1><p>{active==='Быстрый доступ'?'Ваши любимые сайты в одном месте':active==='Избранное'?'Сайты, которые вы отметили звездой':'Ваша подборка сайтов'}</p></div><button className="add-button" onClick={()=>setAddOpen(true)}><Plus size={18}/> Добавить сайт</button></div>
   <div className="toolbar"><div className="tabs"><button className={active==='Быстрый доступ'?'selected':''} onClick={()=>setActive('Быстрый доступ')}>Все сайты <b>{sites.length}</b></button><button className={active==='Избранное'?'selected':''} onClick={()=>setActive('Избранное')}>Избранное <b>{sites.filter(s=>s.favorite).length}</b></button><button className={active==='Недавние'?'selected':''} onClick={()=>setActive('Недавние')}>Недавние</button></div><div className="tools"><button className={view==='grid'?'on':''} onClick={()=>setView('grid')}><Grid2X2 size={17}/></button><button className={view==='list'?'on':''} onClick={()=>setView('list')}><List size={18}/></button><span className="divider"></span><button onClick={()=>setSettings(true)}><SlidersHorizontal size={17}/> Вид</button><button className={multiSelect?'on':''} onClick={()=>{setMultiSelect(v=>!v);setSelectedMany([])}}><Check size={16}/> Выбрать</button><button><MoreHorizontal size={18}/></button></div></div>
   {multiSelect&&selectedMany.length>0&&<div className="bulk-bar glass"><b>{selectedMany.length} выбрано</b><button onClick={()=>{const target=prompt('Переместить в категорию:',categories[0]);if(target&&categories.includes(target)){setSites(x=>x.map(item=>selectedMany.includes(item.title)?{...item,category:target}:item));setSelectedMany([]);setToast('Сайты перемещены')}}}><Folder size={14}/> Переместить</button><button onClick={()=>{setSites(x=>x.filter(item=>!selectedMany.includes(item.title)));setSelectedMany([]);setToast('Выбранные сайты удалены')}}><Trash2 size={14}/> Удалить</button><button onClick={()=>setSelectedMany([])}>Снять выбор</button></div>}{active==='Заметки'?<NotesWorkspace sites={sites.filter(s=>s.note)} onEdit={setEditing}/>:filtered.length?<div className={'site-grid '+(view==='list'?'list-view':'')} style={{gap:density}}>{filtered.map(site=><SiteTile key={site.title} site={site} selected={selected===site.title} onSelect={()=>setSelected(site.title)} onFav={()=>toggleFav(site.title)} onToast={setToast} onEdit={()=>setEditing(site)} onDragStart={()=>setDragged(site.title)} onDragEnd={()=>setDragged(null)} onDrop={()=>reorder(site.title)} selectionMode={multiSelect} selectedMany={selectedMany.includes(site.title)} onToggleSelect={()=>setSelectedMany(x=>x.includes(site.title)?x.filter(n=>n!==site.title):[...x,site.title])} showDescription={tile.showDescription} showDomain={tile.showDomain} onDelete={()=>{setSites(x=>x.filter(item=>item.title!==site.title));setToast('Сайт удалён')}} onOpen={()=>{const opened={...site,lastOpened:Date.now()};setSites(x=>x.map(item=>item.title===site.title?opened:item));setHistory(x=>[site.title,...x.filter(n=>n!==site.title)].slice(0,20));window.open('https://'+site.domain,'_blank','noopener,noreferrer')}}/>)}<button className="add-card" onClick={()=>setAddOpen(true)}><Plus size={22}/><b>Добавить сайт</b><span>Сохранить новую ссылку</span></button></div>:<div className="empty"><Search size={30}/><b>Ничего не найдено</b><span>Попробуйте изменить запрос</span></div>}
  </main>
  <div className="favorites-dock glass" aria-label="Избранные сайты">{sites.filter(s=>s.favorite).slice(0,7).map(site=><button key={site.title} title={site.title} draggable onDragStart={()=>setDragged(site.title)} onDragOver={e=>e.preventDefault()} onDrop={()=>reorder(site.title)} onDragEnd={()=>setDragged(null)} onClick={()=>{setSites(x=>x.map(item=>item.title===site.title?{...item,lastOpened:Date.now()}:item));window.open('https://'+site.domain,'_blank')}}><span style={{background:site.color}}>{site.icon}</span><em>{site.title}</em></button>)}</div>
  <nav className="dock glass">{nav.map(([label,Icon])=><button key={label} className={active===label?'dock-active':''} onClick={()=>label==='Настройки'?setSettings(true):setActive(label)}><Icon size={19}/><span>{label}</span></button>)}</nav>
  {settings&&<Settings onClose={()=>setSettings(false)} density={density} setDensity={setDensity} sites={sites} setSites={setSites} ui={ui} setUi={setUi} tile={tile} setTile={setTile} appearance={appearance} setAppearance={setAppearance}/>} {addOpen&&<AddSiteModal categories={categories} onClose={()=>setAddOpen(false)} onSave={site=>{setSites(x=>[site,...x]);setAddOpen(false);setToast('Сайт добавлен')}}/>}{editing&&<AddSiteModal categories={categories} existing={editing} onClose={()=>setEditing(null)} onSave={site=>{setSites(x=>x.map(item=>item.title===editing.title?site:item));setEditing(null);setToast('Сайт обновлён')}}/>} {mobileNav&&<MobileSections items={nav} active={active} setActive={setActive} onClose={()=>setMobileNav(false)}/>} {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
